services:
  auth-db:
    image: mongo:8.0
    container_name: auth-db
    restart: unless-stopped
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: auth_db
    volumes:
      - auth-mongo-data:/data/db

volumes:
  auth-mongo-data:
